-- backup: symptom_severity_rules (32 rows)
-- Migrations 20251214205154 and 20251214211118 insert the same 32 rules with
-- fresh UUIDs. Running this file on top of them would double the table to 64
-- and the symptom evaluator would match each keyword twice. symptom_entries
-- and symptom_red_flags were empty at capture, so nothing references these ids.
-- Replace the seeded rows with this snapshot.

BEGIN;
DELETE FROM public.symptom_severity_rules;

INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('6b988bdd-1689-44be-a899-ffc26723c630','chest pain','chest','severe',1,'critical','{radiating,crushing,"shortness of breath",sweating,nausea}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('3d873f6a-5d34-4a68-a786-d77eb755e43c','shortness of breath','chest','moderate',2,'severe','{"sudden onset","at rest","chest pain","blue lips"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('7cf8bd2d-7a7e-4120-a8fc-330a5c07048b','headache','head','mild',72,'moderate','{"worst ever","sudden onset","stiff neck",fever,confusion}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('575a8e3f-812c-4764-9abb-ca7b01cc4291','abdominal pain','abdomen','mild',24,'moderate','{severe,"rigid abdomen","blood in stool","vomiting blood"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('8db8af0d-0545-4cac-b5b6-642cd14a7ddf','back pain','back','mild',168,'moderate','{numbness,weakness,"bladder problems",fever}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('fa32008d-775e-4321-a70d-06a97e5b833a','fever','general','mild',72,'moderate','{"above 39.5","stiff neck",rash,confusion,"difficulty breathing"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('913a0cc0-8d76-415f-9499-af2a3f74342f','dizziness','head','mild',24,'moderate','{fainting,"chest pain","slurred speech",weakness}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('3ba327a1-ab33-4884-9440-e8f482f09c48','fatigue','general','mild',336,'moderate','{"weight loss","night sweats",unexplained}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('af071ac1-b025-4b0b-989b-926a99b5ae52','joint pain','musculoskeletal','mild',168,'moderate','{swelling,redness,"hot to touch",fever}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('6c1aa4c5-24d2-4c5f-a4bc-539279f8a1ec','numbness','neurological','moderate',24,'severe','{"sudden onset","one side","facial drooping","speech problems"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('6ee1819d-d6ba-4bd1-9988-67ed96ca07da','chest pain','chest','severe',2,'critical','{radiating,crushing,"shortness of breath",sweating,"left arm"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('a48f1f33-49bd-4e69-8d66-f042e3ba6d8e','chest tightness','chest','moderate',4,'severe','{"difficulty breathing",palpitations}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('c857d71f-1b4d-40cd-ad3a-bc1ad681c06c','headache','head','mild',72,'moderate','{"worst headache","sudden onset",confusion,"vision changes","neck stiffness"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('c942646b-de9d-41a1-9aeb-9d80befc4f77','migraine','head','moderate',24,'severe','{"vision loss",numbness,weakness}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('103c177f-9c4f-4f67-ae21-c72d79a6d3d8','dizziness','head','mild',48,'moderate','{fainting,confusion,"chest pain"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('5ff23121-8995-4947-a662-5ea891b4ad03','abdominal pain','abdomen','mild',24,'moderate','{"blood in stool","vomiting blood","rigid abdomen","high fever"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('d329830b-f809-4de8-8df0-c73daf8fb4e7','stomach pain','abdomen','mild',24,'moderate','{blood,"unable to keep fluids","severe cramping"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('6ae3b970-c9f0-47fd-82a6-66b1e70ab976','nausea','abdomen','mild',48,'moderate','{"blood in vomit","severe dehydration"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('d53f6569-8041-4c25-bd91-d67d18dcb87c','shortness of breath','chest','moderate',2,'severe','{"blue lips","unable to speak","chest pain"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('905d5458-5292-4445-8839-c8ad8d9214b3','difficulty breathing','chest','severe',1,'critical','{gasping,choking,unconscious}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('93a223bc-8011-4141-9f3a-4a66d808e111','cough','chest','mild',168,'moderate','{blood,"high fever","difficulty breathing"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('6a545a57-7f65-4f4c-aa54-2ceab76a27e0','back pain','back','mild',72,'moderate','{numbness,"weakness in legs","loss of bladder control"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('26d80e2b-a056-46a0-8f86-d29ee3ed75ed','neck pain','neck','mild',48,'moderate','{stiffness,"high fever",numbness}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('f7843f9e-9916-4c94-a0b9-073f0e86da1c','joint pain','musculoskeletal','mild',72,'moderate','{swelling,redness,fever,"inability to move"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('63384d89-b4e5-4441-94ed-8a41dedb2918','anxiety','mental','mild',168,'moderate','{"panic attack","suicidal thoughts",self-harm}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('4e14827d-f67c-4223-b393-615a4b86143b','depression','mental','moderate',336,'severe','{"suicidal thoughts",self-harm,"unable to function"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('9d5b0cd9-5cb2-4295-9ef9-36df2ca15689','rash','skin','mild',48,'moderate','{"spreading rapidly","high fever","difficulty breathing",swelling}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('d820cf1a-613d-466f-8a86-21321273364e','swelling','skin','mild',24,'moderate','{throat,"difficulty breathing",face}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('3b2ff1dd-92ea-42f1-8937-2a1b84aa10f4','fever','general','mild',72,'moderate','{"above 39C","above 103F",confusion,"stiff neck",rash}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('f9c4728b-fc6d-4a9a-b5c8-3d3f3d565cb7','high temperature','general','mild',48,'moderate','{convulsions,confusion}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('107fa3b7-370c-458e-beb1-c3dfc0b857cf','fatigue','general','mild',336,'moderate','{"sudden onset","weight loss","night sweats"}','t');
INSERT INTO public.symptom_severity_rules (id,symptom_keyword,body_region,base_severity,duration_hours_threshold,escalation_severity,red_flag_triggers,is_active) VALUES ('bc49436b-1779-463b-bca5-fe2d8a26b648','weakness','general','mild',48,'moderate','{sudden,one-sided,"facial drooping","slurred speech"}','t');

COMMIT;
