export const PROFESSIONAL_PHRASES: Record<string, string[]> = {
  'physiotherapist': ['physical therapy', 'rehabilitation', 'movement therapy'],
  'biokineticist': ['biokinetics', 'exercise therapy', 'rehabilitation'],
  'dietician': ['nutritional guidance', 'meal planning', 'dietary advice'],
  'personal-trainer': ['fitness coaching', 'personal training', 'exercise guidance'],
  'coaching': ['life coaching', 'wellness coaching', 'personal development'],
  'psychology': ['mental health support', 'counseling', 'psychotherapy'],
  'psychiatry': ['psychiatric evaluation', 'medication management', 'mental health treatment'],
  'family-medicine': ['general health check', 'family care', 'primary care'],
  'pain-management': ['pain relief strategies', 'chronic pain management', 'pain assessment'],
  'podiatrist': ['foot care', 'podiatric treatment', 'foot health'],
  'general-practitioner': ['GP consultation', 'primary health care', 'family doctor'],
  'sport-physician': ['sports medicine', 'athletic care', 'sports injury management'],
  'orthopedic-surgeon': ['orthopedic surgery', 'joint care', 'musculoskeletal treatment'],
  'gastroenterology': ['digestive health', 'gastrointestinal care', 'stomach issues'],
  'massage-therapy': ['therapeutic massage', 'relaxation massage', 'sports massage'],
  'nutrition-coaching': ['nutrition advice', 'dietary coaching', 'healthy eating guidance'],
  'occupational-therapy': ['occupational rehabilitation', 'functional therapy', 'daily living skills'],
  'physical-therapy': ['rehabilitation therapy', 'physical rehabilitation', 'movement therapy'],
  'chiropractor': ['spinal manipulation', 'chiropractic care', 'back pain treatment'],
  'nurse-practitioner': ['nursing care', 'health assessments', 'patient education'],
  'cardiology': ['heart health', 'cardiac care', 'heart disease management'],
  'dermatology': ['skin care', 'dermatological treatment', 'skin health'],
  'neurology': ['nervous system care', 'neurological assessment', 'brain health'],
  'endocrinology': ['hormonal health', 'diabetes management', 'thyroid care'],
  'urology': ['urinary health', 'male reproductive health', 'kidney care'],
  'oncology': ['cancer care', 'oncological treatment', 'tumor management'],
  'rheumatology': ['joint health', 'arthritis management', 'autoimmune care'],
  'pediatrics': ['child health', 'pediatric care', 'children’s health'],
  'geriatrics': ['elderly care', 'geriatric health', 'aging-related care'],
  'sports-medicine': ['sports injury treatment', 'athletic health', 'exercise rehabilitation'],
  'internal-medicine': ['internal health', 'adult medicine', 'chronic disease management'],
  'orthopedics': ['bone health', 'musculoskeletal care', 'joint treatment'],
  'neurosurgery': ['brain surgery', 'neurological surgery', 'spinal surgery'],
  'infectious-disease': ['infection management', 'disease control', 'public health'],
  'plastic-surgery': ['cosmetic surgery', 'reconstructive surgery', 'aesthetic procedures'],
  'obstetrics-gynecology': ['women’s health', 'pregnancy care', 'gynecological health'],
  'emergency-medicine': ['emergency care', 'urgent health issues', 'trauma care'],
  'anesthesiology': ['anesthesia management', 'pain control', 'surgical anesthesia'],
  'radiology': ['imaging services', 'diagnostic imaging', 'radiological assessments'],
  'geriatric-medicine': ['elderly health care', 'geriatric assessments', 'aging care'],
  'strength-coaching': ['strength training', 'fitness coaching', 'muscle building'],
  'run-coaching': ['running training', 'endurance coaching', 'marathon preparation'],
  'all': ['general health services', 'comprehensive care', 'holistic health']
};
