import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// Input validation schemas
interface RequestBody {
  message: string;
  context?: Record<string, unknown>;
}

function validateInput(body: unknown): { valid: boolean; data?: RequestBody; error?: string } {
  if (!body || typeof body !== 'object') {
    return { valid: false, error: 'Request body must be an object' };
  }
  
  const { message, context } = body as Record<string, unknown>;
  
  if (typeof message !== 'string') {
    return { valid: false, error: 'Message must be a string' };
  }
  
  if (message.length === 0) {
    return { valid: false, error: 'Message cannot be empty' };
  }
  
  if (message.length > 5000) {
    return { valid: false, error: 'Message exceeds maximum length of 5000 characters' };
  }
  
  if (context !== undefined && (typeof context !== 'object' || context === null)) {
    return { valid: false, error: 'Context must be an object if provided' };
  }
  
  return { 
    valid: true, 
    data: { 
      message: message.trim(),
      context: context as Record<string, unknown> | undefined
    } 
  };
}

// Sanitize data for logging (remove sensitive info)
function sanitizeForLogging(data: Record<string, unknown>): Record<string, unknown> {
  const sanitized = { ...data };
  // Remove potentially sensitive fields
  delete sanitized.authorization;
  delete sanitized.apikey;
  delete sanitized.password;
  delete sanitized.token;
  return sanitized;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  // Only allow POST requests
  if (req.method !== 'POST') {
    return new Response(
      JSON.stringify({ error: 'Method not allowed' }),
      { status: 405, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  try {
    // Parse and validate input
    let body: unknown;
    try {
      body = await req.json();
    } catch {
      return new Response(
        JSON.stringify({ error: 'Invalid JSON body' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const validation = validateInput(body);
    if (!validation.valid || !validation.data) {
      console.log('[ai-health-assistant] Validation failed:', validation.error);
      return new Response(
        JSON.stringify({ error: validation.error }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const { message, context } = validation.data;
    
    // Get and validate authorization header
    const authHeader = req.headers.get('Authorization');
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      console.log('[ai-health-assistant] Missing or invalid authorization header');
      return new Response(
        JSON.stringify({ error: 'Missing or invalid authorization header' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Initialize Supabase client with user's JWT
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    );

    // Verify the user is authenticated
    const { data: { user }, error: authError } = await supabaseClient.auth.getUser();
    if (authError || !user) {
      console.log('[ai-health-assistant] Authentication failed:', authError?.message ?? 'No user');
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Log request (sanitized)
    console.log('[ai-health-assistant] Processing request for user:', user.id, 'message_length:', message.length);

    // Generate response (placeholder for AI integration)
    const response = {
      message: `AI Health Assistant Response: Based on your query, I recommend consulting with healthcare professionals. This is a demo response that would normally be generated by an AI model.`,
      recommendations: [
        "Consult with a healthcare professional",
        "Consider lifestyle modifications",
        "Regular health monitoring"
      ],
      timestamp: new Date().toISOString(),
      userId: user.id
    };

    // Log the interaction (audit trail)
    const { error: insertError } = await supabaseClient
      .from('ai_interactions')
      .insert({
        user_id: user.id,
        user_message: message,
        ai_response: response.message,
        context: context ?? null
      });

    if (insertError) {
      // Log error but don't fail the request
      console.error('[ai-health-assistant] Failed to log interaction:', insertError.message);
    }

    console.log('[ai-health-assistant] Request completed successfully for user:', user.id);

    return new Response(
      JSON.stringify(response),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    // Safe error logging (don't expose internal details)
    console.error('[ai-health-assistant] Internal error:', error instanceof Error ? error.message : 'Unknown error');
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
