
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { message, context } = await req.json()
    
    // Get the authorization header
    const authHeader = req.headers.get('Authorization')!
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    )

    // Verify the user is authenticated
    const { data: { user }, error: authError } = await supabaseClient.auth.getUser()
    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // This is a placeholder for AI processing
    // In a real implementation, you would integrate with OpenAI, Anthropic, or another AI service
    const response = {
      message: `AI Health Assistant Response: Based on your query "${message}", I recommend consulting with healthcare professionals. This is a demo response that would normally be generated by an AI model.`,
      recommendations: [
        "Consult with a healthcare professional",
        "Consider lifestyle modifications",
        "Regular health monitoring"
      ],
      timestamp: new Date().toISOString(),
      userId: user.id
    }

    // Log the interaction
    await supabaseClient
      .from('ai_interactions')
      .insert({
        user_id: user.id,
        user_message: message,
        ai_response: response.message,
        context: context
      })

    return new Response(
      JSON.stringify(response),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
