
// Common mapping data used across analyzer components
export type KeywordMapping = Record<string, string[]>;

// Goal to service mappings
export const GOAL_TO_SERVICES: Record<string, string[]> = {
  'weight loss': ['personal-trainer', 'dietician', 'coaching'],
  'fitness goals': ['personal-trainer', 'coaching', 'dietician'],
  'strength': ['personal-trainer', 'physiotherapist'],
  'muscle': ['personal-trainer', 'dietician'],
  'nutrition': ['dietician', 'personal-trainer', 'coaching'],
  'recovery': ['physiotherapist', 'personal-trainer'],
  'pain management': ['physiotherapist', 'family-medicine', 'pain-management'],
  'fitness': ['personal-trainer', 'coaching', 'dietician'],
  'health': ['family-medicine', 'dietician', 'personal-trainer'],
  'cardio': ['personal-trainer', 'coaching'],
  'energy': ['dietician', 'personal-trainer', 'endocrinology'],
  'stress': ['coaching', 'physiotherapist', 'psychiatry'],
  'performance': ['personal-trainer', 'coaching', 'physiotherapist'],
  'rehabilitation': ['physiotherapist', 'personal-trainer'],
  'endurance': ['personal-trainer', 'coaching'],
  'stomach pain': ['gastroenterology', 'family-medicine'],
  'stomach issues': ['gastroenterology', 'family-medicine'],
  'digestive problems': ['gastroenterology', 'family-medicine'],
  'anxiety': ['psychiatry', 'coaching'],
  'depression': ['psychiatry', 'coaching'],
  'mental health': ['psychiatry', 'coaching'],
  'sleep issues': ['psychiatry', 'family-medicine'],
  'headaches': ['neurology', 'family-medicine'],
  'joint pain': ['physiotherapist', 'orthopedics', 'rheumatology'],
  'skin issues': ['dermatology', 'family-medicine']
};

// Symptom to condition mappings
export const SYMPTOM_TO_CONDITION: Record<string, string[]> = {
  'weight': ['weight loss'],
  'diet': ['weight loss'],
  'nutrition': ['weight loss'],
  'lose weight': ['weight loss'],
  'kg': ['weight loss'],
  'tone': ['fitness goals'],
  'toning': ['fitness goals'],
  'train': ['fitness goals'],
  'training': ['fitness goals'],
  'workout': ['fitness goals'],
  'exercise': ['fitness goals'],
  'fitness': ['fitness goals'],
  'blood pressure': ['hypertension'],
  'high blood pressure': ['hypertension'],
  'pressure': ['hypertension'],
  'sugar': ['diabetes'],
  'diabetes': ['diabetes'],
  'glucose': ['diabetes'],
  'breathing': ['asthma'],
  'breathe': ['asthma'],
  'inhaler': ['asthma'],
  'ankle': ['ankle sprain'],
  'sprain': ['ankle sprain'],
  'shoulder': ['shoulder strain'],
  'strain': ['shoulder strain'],
  'tired': ['chronic fatigue'],
  'fatigue': ['chronic fatigue'],
  'exhausted': ['chronic fatigue'],
  'stomach': ['stomach issues'],
  'digestive': ['stomach issues'],
  'gut': ['stomach issues'],
  'stomach pain': ['stomach issues'],
  "doesn't feel good": ['stomach issues'],
  'nausea': ['stomach issues'],
  'vomiting': ['stomach issues'],
  'diarrhea': ['stomach issues'],
  'constipation': ['stomach issues'],
  'bloating': ['stomach issues'],
  'indigestion': ['stomach issues'],
  'knee': ['knee pain'],
  'back': ['back pain'],
  'spine': ['back pain'],
  'stress': ['mental health'],
  'anxiety': ['mental health', 'anxiety'],
  'depression': ['mental health', 'depression'],
  'mental': ['mental health'],
  'sleep': ['sleep issues'],
  'insomnia': ['sleep issues'],
  'headache': ['headaches'],
  'migraine': ['headaches'],
  'joint': ['joint pain'],
  'arthritis': ['joint pain'],
  'inflammation': ['joint pain'],
  'skin': ['skin issues'],
  'rash': ['skin issues'],
  'acne': ['skin issues'],
  'eczema': ['skin issues'],
  'wedding': ['fitness goals', 'weight loss']
};

// Timeframe keywords - for detecting how urgently the user needs results
export const TIMEFRAME_KEYWORDS: Record<string, string> = {
  'urgent': 'immediate',
  'asap': 'immediate',
  'right away': 'immediate',
  'immediately': 'immediate',
  'as soon as possible': 'immediate',
  'this week': 'days',
  'few days': 'days',
  'next week': 'weeks',
  'couple weeks': 'weeks',
  'two weeks': 'weeks',
  'few weeks': 'weeks',
  'month': 'month',
  'four weeks': 'month',
  'couple months': 'months',
  'few months': 'months',
  'several months': 'months',
  'half year': 'months',
  'year': 'year',
  'long term': 'year',
  'wedding': 'months',
  'event': 'months' 
};

// Complexity indicators - words that suggest multiple issues
export const COMPLEXITY_INDICATORS: string[] = [
  'chronic',
  'multiple',
  'several issues',
  'complex',
  'complicated',
  'and also',
  'as well as',
  'combination',
  'history of',
  'recurring',
  'persistent',
  'ongoing',
  'long-term',
  'years',
  'since childhood'
];
