// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import {
  SUPABASE_URL as RESOLVED_SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY as RESOLVED_SUPABASE_PUBLISHABLE_KEY,
} from './env';

// Resolved through ./env, which reads VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY
// and falls back to a known good project when the build has no env vars baked in.
// Reading import.meta.env directly here crashed every page in production on
// 2026-09-22: createClient throws "supabaseUrl is required" at module load, React
// never mounts, and the whole site degrades to its prerendered HTML shell.
const SUPABASE_URL = RESOLVED_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = RESOLVED_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
